macro(create_source_groups ROOT_DIRECTORY)
    set(PATH_LIST)
    foreach(SOURCE_FILE ${ARGN})
        get_filename_component(SOURCE_PATH ${SOURCE_FILE} PATH)
        list(APPEND PATH_LIST ${SOURCE_PATH})
    endforeach()
    list(SORT PATH_LIST)
    list(REMOVE_DUPLICATES PATH_LIST)
    foreach(GROUP_PATH ${PATH_LIST})
        set(CONTAINED_SOURCES)
        foreach(SOURCE_FILE ${ARGN})
            get_filename_component(SOURCE_PATH ${SOURCE_FILE} PATH)
            if (${SOURCE_PATH} STREQUAL ${GROUP_PATH})
                list(APPEND CONTAINED_SOURCES ${SOURCE_FILE})
            endif()
        endforeach()
        string(REPLACE "${ROOT_DIRECTORY}/" "" STRIPPED_PATH ${GROUP_PATH})
        string(REGEX REPLACE "/" "\\\\" GROUP_NAME ${STRIPPED_PATH})
        source_group(${GROUP_NAME} FILES ${CONTAINED_SOURCES})
    endforeach()
endmacro()
